version: "2"
services:
  mysql:
    image: "mysql"
    container_name: "mysql"
    env_file: "/home/ryt/Projects/codex/settings/mysql.conf"
    volumes:
    - /opt/data:/var/lib/mysql
    ports:
    - 3306:3306
