# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-09 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20170709_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsentry',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
